//! User configuration: `%APPDATA%\apex\config.toml`.
//!
//! Hand-rolled parser for a small TOML subset - `[section]`, `key = value`,
//! `#` comments, quoted strings, booleans. No dependencies, no allocation
//! beyond the parsed map. A missing file is created with commented defaults
//! so the options are discoverable.

use std::collections::HashMap;
use std::path::PathBuf;

/// Config section listing extra folders to index.
pub const SOURCES: &str = "sources";

// MOD_CONTROL / VK_ESCAPE as plain integers to keep this module POD.
pub const DEFAULT_HOTKEY_MODS: u32 = 0x0002;
pub const DEFAULT_HOTKEY_VK: u32 = 0x1B;

const DEFAULT_FILE: &str = r#"# Apex configuration
# Changes take effect on restart.

[general]
# Create/refresh a Start menu entry for apex on launch.
start_menu = true
# Launch apex automatically at sign-in.
start_on_startup = true
# Show a tray icon (right-click for Open / Reload / Config / Quit).
tray_icon = true
# Run apex elevated, via a scheduled logon task, so the hotkey still works
# while an elevated window (Task Manager) has focus. Enabling it asks for
# admin once to create the task, and takes effect at the next sign-in.
# Apps you launch are handed to Explorer so they still run unelevated.
run_as_admin = false

[hotkey]
# Modifiers joined with '+': ctrl, alt, shift, win. Use "none" for bare keys.
modifiers = "ctrl"
# Key: a-z, 0-9, f1-f24, space, escape, tab, grave, enter
key = "escape"

[plugins]
# Set to false to disable a plugin entirely; a disabled plugin is never
# constructed and uses zero memory.
search = true
quicklinks = true
# Apex's own commands, e.g. "Reload Apex" - which re-reads this file and
# rescans installed applications without a restart.
commands = true

# Quicklinks open a link, folder or program by name. Create and edit them
# from inside apex with Ctrl+K, or write them here by hand:
#
#   [quicklinks.github]
#   name = 'Search GitHub'
#   link = 'https://github.com/search?q={query}'
#   open_with = 'chrome'        # optional; defaults to the system handler
#
# A {token} in the link makes the quicklink take an argument: running it
# asks for a value using the token's name, then substitutes it in.
# Prefer 'single quotes' - they keep Windows paths like C:\tools\x.exe
# literal, with no escaping.

# Extra folders to index, alongside the Start menu. Scanned one level deep
# for .exe, .lnk, .bat, .cmd and .ps1 - handy for portable apps. Add one
# with "Apex: Add Source Folder", or by hand here, then reload.
#
#   [sources]
#   1 = 'D:\PortableApps'

# Entries removed from apex, as plugin/payload. Written by the "Hide from
# Apex" action; review them with "Apex: Manage Hidden Entries". The keys are
# just indices - a bare TOML key cannot hold a path or a {GUID}.
#
#   [hidden]
#   1 = 'search/C:\Windows\system32\some-tool.exe'
"#;

pub struct Config {
    values: HashMap<(String, String), String>,
    pub hotkey_mods: u32,
    pub hotkey_vk: u32,
}

impl Config {
    pub fn load() -> Self {
        let text = read_or_create().unwrap_or_default();
        Self::from_text(&text)
    }

    pub(crate) fn from_text(text: &str) -> Self {
        let values = parse(text);
        let (hotkey_mods, hotkey_vk) =
            hotkey_from(&values).unwrap_or((DEFAULT_HOTKEY_MODS, DEFAULT_HOTKEY_VK));
        Self {
            values,
            hotkey_mods,
            hotkey_vk,
        }
    }

    /// Plugins default to enabled when not mentioned in the file.
    pub fn plugin_enabled(&self, id: &str) -> bool {
        match self.values.get(&("plugins".to_string(), id.to_lowercase())) {
            Some(v) => v.eq_ignore_ascii_case("true"),
            None => true,
        }
    }

    /// Boolean from the `[general]` section with a default.
    pub fn general_flag(&self, key: &str, default: bool) -> bool {
        match self.values.get(&("general".to_string(), key.to_string())) {
            Some(v) => v.eq_ignore_ascii_case("true"),
            None => default,
        }
    }

    /// `[aliases]` entries: alias (lowercased by the parser) -> app id.
    pub fn aliases_map(&self) -> HashMap<String, String> {
        self.values
            .iter()
            .filter(|((section, _), _)| section == "aliases")
            .map(|((_, alias), app_id)| (alias.clone(), app_id.clone()))
            .collect()
    }

    /// Values of a numbered-key section, in key order.
    ///
    /// ```toml
    /// [hidden]
    /// 1 = 'Microsoft.AutoGenerated.{CB51...}'
    /// 2 = 'C:\tools\thing.exe'
    /// ```
    ///
    /// The keys are just indices: a bare TOML key cannot hold a Windows path
    /// or a `{GUID}`, so the payload has to live on the value side.
    pub fn list_values(&self, section: &str) -> Vec<String> {
        let mut items: Vec<(u32, &String)> = self
            .values
            .iter()
            .filter(|((s, _), _)| s == section)
            .filter_map(|((_, k), v)| Some((k.parse().ok()?, v)))
            .collect();
        items.sort_by_key(|(n, _)| *n);
        items.into_iter().map(|(_, v)| v.clone()).collect()
    }

    /// One-level sub-tables under `prefix`, e.g. `[quicklinks.github]` for
    /// prefix `quicklinks` yields `("github", {name: .., link: ..})`.
    ///
    /// Sorted by slug so the order is stable across runs - `values` is a
    /// HashMap, whose iteration order is randomised.
    pub fn subtables(&self, prefix: &str) -> Vec<(String, HashMap<String, String>)> {
        let head = format!("{prefix}.");
        let mut grouped: HashMap<String, HashMap<String, String>> = HashMap::new();
        for ((section, key), value) in &self.values {
            let Some(slug) = section.strip_prefix(&head) else {
                continue;
            };
            if slug.is_empty() || slug.contains('.') {
                continue;
            }
            grouped
                .entry(slug.to_string())
                .or_default()
                .insert(key.clone(), value.clone());
        }
        let mut out: Vec<_> = grouped.into_iter().collect();
        out.sort_by(|a, b| a.0.cmp(&b.0));
        out
    }
}

// ---- alias write-back -------------------------------------------------
//
// The config file is user-owned (often symlinked into dotfiles), so writes
// are line-surgery on the `[aliases]` section only; everything else,
// including comments, is preserved byte-for-byte.

/// Insert or replace an alias line. Removes any previous line with the same
/// alias or the same app id (one alias per app).
fn upsert_alias_text(text: &str, alias: &str, app_id: &str) -> String {
    let mut lines = drop_alias_lines(text, |k, v| k == alias || v == app_id);
    let new_line = format!("{alias} = \"{app_id}\"");
    match alias_section_end(&lines) {
        Some(idx) => lines.insert(idx, new_line),
        None => {
            if !lines.last().is_none_or(|l| l.trim().is_empty()) {
                lines.push(String::new());
            }
            lines.push("[aliases]".to_string());
            lines.push(new_line);
        }
    }
    join_lines(lines)
}

/// Remove every alias pointing at `app_id`.
fn remove_alias_text(text: &str, app_id: &str) -> String {
    join_lines(drop_alias_lines(text, |_, v| v == app_id))
}

/// Lines of `text` minus `[aliases]` entries matching `drop(key, value)`.
fn drop_alias_lines(text: &str, drop: impl Fn(&str, &str) -> bool) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_aliases = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if let Some(name) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_aliases = name.trim().eq_ignore_ascii_case("aliases");
        } else if in_aliases {
            if let Some((k, v)) = trimmed.split_once('=') {
                if drop(&k.trim().to_lowercase(), unquote(v.trim())) {
                    continue;
                }
            }
        }
        out.push(line.to_string());
    }
    out
}

/// Index just past the last non-blank line of `[section]`, if present.
fn section_end(lines: &[String], section: &str) -> Option<usize> {
    let mut inside = false;
    let mut end = None;
    for (i, line) in lines.iter().enumerate() {
        if let Some(name) = header_name(line) {
            if inside {
                break;
            }
            inside = name.eq_ignore_ascii_case(section);
            if inside {
                end = Some(i + 1);
            }
        } else if inside && !line.trim().is_empty() {
            end = Some(i + 1);
        }
    }
    end
}

fn alias_section_end(lines: &[String]) -> Option<usize> {
    section_end(lines, "aliases")
}

/// Insert or replace a single `key = value` line inside `[section]`.
///
/// Line surgery, like the alias and quicklink writers: every other line,
/// comments included, is preserved byte-for-byte. A trailing comment on the
/// replaced line is carried over rather than silently dropped.
fn upsert_key_text(text: &str, section: &str, key: &str, value: &str) -> String {
    let new_line = format!("{key} = {value}");
    let mut lines: Vec<String> = Vec::new();
    let mut inside = false;
    let mut replaced = false;

    for line in text.lines() {
        if let Some(name) = header_name(line) {
            inside = name.eq_ignore_ascii_case(section);
        } else if inside
            && !replaced
            && strip_comment(line)
                .split_once('=')
                .is_some_and(|(k, _)| k.trim().eq_ignore_ascii_case(key))
        {
            let comment = line[strip_comment(line).len()..].trim();
            lines.push(if comment.is_empty() {
                new_line.clone()
            } else {
                format!("{new_line}  {comment}")
            });
            replaced = true;
            continue;
        }
        lines.push(line.to_string());
    }

    if !replaced {
        match section_end(&lines, section) {
            Some(idx) => lines.insert(idx, new_line),
            None => {
                if !lines.last().is_none_or(|l| l.trim().is_empty()) {
                    lines.push(String::new());
                }
                lines.push(format!("[{section}]"));
                lines.push(new_line);
            }
        }
    }
    join_lines(lines)
}

/// Persist a `[general]` boolean.
pub fn set_general_flag_file(key: &str, value: bool) {
    let v = if value { "true" } else { "false" };
    edit_config_file(|text| upsert_key_text(text, "general", key, v));
}

fn join_lines(lines: Vec<String>) -> String {
    let mut s = lines.join("\n");
    s.push('\n');
    s
}

// ---- whole-section write-back -----------------------------------------
//
// Quicklinks are sub-tables rather than single lines, so they are edited a
// block at a time. Same rule as aliases: everything outside the block,
// comments included, is preserved byte-for-byte.

/// The section name of a `[header]` line, if this line is one.
fn header_name(line: &str) -> Option<&str> {
    line.trim()
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .map(str::trim)
}

/// Lines of `text` with the whole `[section]` block removed.
fn drop_section_lines(text: &str, section: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_target = false;
    for line in text.lines() {
        if let Some(name) = header_name(line) {
            in_target = name.eq_ignore_ascii_case(section);
        }
        if !in_target {
            out.push(line.to_string());
        }
    }
    out
}

fn trim_trailing_blanks(lines: &mut Vec<String>) {
    while lines.last().is_some_and(|l| l.trim().is_empty()) {
        lines.pop();
    }
}

/// Replace a `[section]` block, or append it if absent. Appending at the end
/// is always safe: a table header closes whatever section preceded it.
fn upsert_section_text(text: &str, section: &str, entries: &[(&str, &str)]) -> String {
    let mut lines = drop_section_lines(text, section);
    trim_trailing_blanks(&mut lines);
    lines.push(String::new());
    lines.push(format!("[{section}]"));
    for (key, value) in entries {
        if !value.is_empty() {
            lines.push(format!("{key} = {}", quote(value)));
        }
    }
    join_lines(lines)
}

fn remove_section_text(text: &str, section: &str) -> String {
    let mut lines = drop_section_lines(text, section);
    trim_trailing_blanks(&mut lines);
    join_lines(lines)
}

/// Rewrite a numbered-key section from scratch, renumbering from 1.
///
/// Whole-section replacement rather than per-line surgery: the keys are
/// positional, so removing one entry would otherwise leave a gap.
pub fn set_list_file(section: &str, values: &[String]) {
    let keys: Vec<(String, String)> = values
        .iter()
        .enumerate()
        .map(|(i, v)| ((i + 1).to_string(), v.clone()))
        .collect();
    let entries: Vec<(&str, &str)> = keys
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    edit_config_file(|text| upsert_section_text(text, section, &entries));
}

pub fn upsert_quicklink_file(slug: &str, entries: &[(&str, &str)]) {
    let section = format!("quicklinks.{slug}");
    edit_config_file(|text| upsert_section_text(text, &section, entries));
}

pub fn remove_quicklink_file(slug: &str) {
    let section = format!("quicklinks.{slug}");
    edit_config_file(|text| remove_section_text(text, &section));
}

fn edit_config_file(edit: impl Fn(&str) -> String) {
    let Some(path) = config_path() else { return };
    let text = std::fs::read_to_string(&path).unwrap_or_else(|_| DEFAULT_FILE.to_string());
    let _ = std::fs::write(&path, edit(&text));
}

pub fn upsert_alias_file(alias: &str, app_id: &str) {
    edit_config_file(|text| upsert_alias_text(text, alias, app_id));
}

pub fn remove_alias_file(app_id: &str) {
    edit_config_file(|text| remove_alias_text(text, app_id));
}

/// Reduce free text to a bare TOML key: lowercase, spaces to `-`, keep only
/// `a-z 0-9 - _ .`. Used for both alias names and quicklink slugs, which are
/// written as bare keys and section names respectively.
pub fn sanitize_key(text: &str) -> String {
    text.trim()
        .to_lowercase()
        .chars()
        .filter_map(|c| match c {
            'a'..='z' | '0'..='9' | '-' | '_' | '.' => Some(c),
            ' ' => Some('-'),
            _ => None,
        })
        .collect()
}

/// Strip characters that the writer cannot represent. [`quote`] falls back to
/// a basic string when a value contains `'`, so a value containing both quote
/// styles would be unrepresentable; double quotes are the rarer of the two in
/// names and links, so they lose.
pub fn sanitize_value(text: &str) -> String {
    text.trim()
        .chars()
        .filter(|c| *c != '"' && !c.is_control())
        .collect()
}

pub fn config_path() -> Option<PathBuf> {
    let appdata = std::env::var_os("APPDATA")?;
    Some(PathBuf::from(appdata).join("apex").join("config.toml"))
}

fn read_or_create() -> Option<String> {
    let path = config_path()?;
    match std::fs::read_to_string(&path) {
        Ok(text) => Some(text),
        Err(_) => {
            if let Some(dir) = path.parent() {
                let _ = std::fs::create_dir_all(dir);
            }
            let _ = std::fs::write(&path, DEFAULT_FILE);
            Some(DEFAULT_FILE.to_string())
        }
    }
}

fn parse(text: &str) -> HashMap<(String, String), String> {
    let mut out = HashMap::new();
    let mut section = String::new();
    for raw in text.lines() {
        let line = strip_comment(raw).trim().to_string();
        if line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            section = name.trim().to_lowercase();
        } else if let Some((k, v)) = line.split_once('=') {
            let key = k.trim().to_lowercase();
            let val = unquote(v.trim()).to_string();
            out.insert((section.clone(), key), val);
        }
    }
    out
}

/// Cut a `#` comment, respecting both quote styles so a `#` inside a link
/// (a URL fragment, say) survives.
fn strip_comment(line: &str) -> &str {
    let mut quote: Option<char> = None;
    for (i, c) in line.char_indices() {
        match c {
            '"' | '\'' => match quote {
                Some(q) if q == c => quote = None,
                Some(_) => {}
                None => quote = Some(c),
            },
            '#' if quote.is_none() => return &line[..i],
            _ => {}
        }
    }
    line
}

/// Strip matched surrounding quotes. No escape processing, in either style -
/// see [`quote`] for why that is deliberate.
fn unquote(v: &str) -> &str {
    for q in ['"', '\''] {
        if let Some(s) = v.strip_prefix(q).and_then(|s| s.strip_suffix(q)) {
            return s;
        }
    }
    v
}

/// Quote a value for writing back to the file.
///
/// Prefers TOML *literal* strings (single quotes), which process no escape
/// sequences - exactly matching this parser, and the only form in which a
/// Windows path like `C:\Users\me` is both valid TOML and round-trips
/// unchanged. Falls back to a basic string when the value contains a single
/// quote; callers strip double quotes beforehand so the two can never clash.
fn quote(v: &str) -> String {
    if v.contains('\'') {
        format!("\"{v}\"")
    } else {
        format!("'{v}'")
    }
}

fn hotkey_from(values: &HashMap<(String, String), String>) -> Option<(u32, u32)> {
    let mods = values.get(&("hotkey".to_string(), "modifiers".to_string()))?;
    let key = values.get(&("hotkey".to_string(), "key".to_string()))?;
    Some((parse_mods(mods)?, parse_key(key)?))
}

fn parse_mods(s: &str) -> Option<u32> {
    let s = s.trim().to_lowercase();
    if s == "none" {
        return Some(0);
    }
    let mut mods = 0u32;
    for part in s.split('+') {
        mods |= match part.trim() {
            "alt" => 0x1,
            "ctrl" | "control" => 0x2,
            "shift" => 0x4,
            "win" | "super" => 0x8,
            _ => return None,
        };
    }
    Some(mods)
}

fn parse_key(s: &str) -> Option<u32> {
    let s = s.trim().to_lowercase();
    let mut chars = s.chars();
    match (chars.next(), chars.next()) {
        (Some(c @ 'a'..='z'), None) => return Some(0x41 + (c as u32 - 'a' as u32)),
        (Some(c @ '0'..='9'), None) => return Some(0x30 + (c as u32 - '0' as u32)),
        _ => {}
    }
    if let Some(n) = s.strip_prefix('f').and_then(|n| n.parse::<u32>().ok()) {
        if (1..=24).contains(&n) {
            return Some(0x70 + n - 1);
        }
    }
    match s.as_str() {
        "space" => Some(0x20),
        "escape" | "esc" => Some(0x1B),
        "tab" => Some(0x09),
        "enter" | "return" => Some(0x0D),
        "grave" | "backtick" | "`" => Some(0xC0),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_sections_comments_quotes() {
        let cfg = Config::from_text(
            "# comment\n[Hotkey]\nmodifiers = \"ctrl+alt\" # trailing\nkey = f19\n\n[plugins]\nsearch = false\n",
        );
        assert_eq!(cfg.hotkey_mods, 0x2 | 0x1);
        assert_eq!(cfg.hotkey_vk, 0x70 + 18);
        assert!(!cfg.plugin_enabled("search"));
        assert!(cfg.plugin_enabled("unlisted"));
    }

    #[test]
    fn defaults_when_missing_or_invalid() {
        for text in ["", "[hotkey]\nmodifiers = \"bogus\"\nkey = \"escape\"\n"] {
            let cfg = Config::from_text(text);
            assert_eq!(cfg.hotkey_mods, DEFAULT_HOTKEY_MODS);
            assert_eq!(cfg.hotkey_vk, DEFAULT_HOTKEY_VK);
        }
    }

    #[test]
    fn default_file_round_trips() {
        let cfg = Config::from_text(DEFAULT_FILE);
        assert_eq!(cfg.hotkey_mods, DEFAULT_HOTKEY_MODS);
        assert_eq!(cfg.hotkey_vk, DEFAULT_HOTKEY_VK);
        assert!(cfg.plugin_enabled("search"));
        assert!(cfg.general_flag("start_menu", true));
        assert!(cfg.general_flag("start_on_startup", true));
    }

    #[test]
    fn reads_quicklink_subtables() {
        let cfg = Config::from_text(
            "[general]\nstart_menu = true\n\n\
             [quicklinks.github]\nname = 'Search GitHub'\nlink = 'https://github.com/search?q={query}'\n\n\
             [quicklinks.dl]\nname = 'Downloads'\nlink = 'C:\\Users\\me\\Downloads'\n\n\
             [quicklinks.deep.nope]\nname = 'ignored'\n",
        );
        let qls = cfg.subtables("quicklinks");
        // Sorted by slug, and the two-level section is not a quicklink.
        assert_eq!(qls.len(), 2);
        assert_eq!(qls[0].0, "dl");
        assert_eq!(qls[1].0, "github");
        assert_eq!(qls[1].1["link"], "https://github.com/search?q={query}");
        // Literal strings keep backslashes intact.
        assert_eq!(qls[0].1["link"], r"C:\Users\me\Downloads");
    }

    #[test]
    fn hash_inside_a_quoted_link_is_not_a_comment() {
        let cfg = Config::from_text("[quicklinks.x]\nlink = 'https://a.dev/docs#install'\n");
        assert_eq!(cfg.subtables("quicklinks")[0].1["link"], "https://a.dev/docs#install");
    }

    #[test]
    fn quicklink_upsert_replaces_only_its_own_block() {
        let text = "# keep me\n[general]\nstart_menu = true\n\n\
                    [quicklinks.gh]\nname = 'Old'\nlink = 'https://old'\n\n\
                    [aliases]\nc = \"Chrome\"\n";
        let out = upsert_section_text(
            text,
            "quicklinks.gh",
            &[("name", "New"), ("link", r"C:\tools\x.exe"), ("open_with", "")],
        );
        assert!(out.contains("# keep me"), "comments outside the block survive");
        assert!(out.contains("c = \"Chrome\""), "other sections survive");
        assert!(!out.contains("Old"));
        assert!(out.contains("name = 'New'"));
        // Empty optional fields are omitted rather than written blank.
        assert!(!out.contains("open_with"));

        let cfg = Config::from_text(&out);
        let qls = cfg.subtables("quicklinks");
        assert_eq!(qls.len(), 1);
        assert_eq!(qls[0].1["link"], r"C:\tools\x.exe");
        assert!(cfg.general_flag("start_menu", false));
        assert_eq!(cfg.aliases_map()["c"], "Chrome");
    }

    #[test]
    fn quicklink_upsert_appends_when_absent_and_remove_deletes() {
        let text = "[general]\nstart_menu = true\n";
        let added = upsert_section_text(text, "quicklinks.new", &[("name", "N"), ("link", "L")]);
        assert_eq!(Config::from_text(&added).subtables("quicklinks").len(), 1);

        let removed = remove_section_text(&added, "quicklinks.new");
        assert!(Config::from_text(&removed).subtables("quicklinks").is_empty());
        assert!(Config::from_text(&removed).general_flag("start_menu", false));
    }

    #[test]
    fn quoting_prefers_literal_strings_and_round_trips() {
        assert_eq!(quote(r"C:\Users\me"), r"'C:\Users\me'");
        assert_eq!(quote("Bob's Site"), "\"Bob's Site\"");
        for v in [r"C:\a\b", "Bob's", "https://x.dev/a#b", "plain"] {
            let line = format!("[s]\nk = {}\n", quote(v));
            assert_eq!(Config::from_text(&line).subtables("").len(), 0);
            assert_eq!(parse(&line)[&("s".to_string(), "k".to_string())], v);
        }
    }

    #[test]
    fn numbered_list_sections_round_trip() {
        let cfg = Config::from_text(
            "[hidden]\n2 = 'second'\n1 = 'C:\\tools\\first.exe'\n3 = 'Auto.{GUID}'\n",
        );
        // Key order, not file order.
        assert_eq!(
            cfg.list_values("hidden"),
            vec![r"C:\tools\first.exe", "second", "Auto.{GUID}"]
        );
        assert!(cfg.list_values("sources").is_empty());
    }

    #[test]
    fn rewriting_a_list_renumbers_and_spares_other_sections() {
        let text = "# top\n[general]\nstart_menu = true\n\n[hidden]\n1 = 'a'\n2 = 'b'\n3 = 'c'\n";
        // Drop the middle entry; the rest must renumber without a gap.
        let values = vec!["a".to_string(), "c".to_string()];
        let keys: Vec<(String, String)> = values
            .iter()
            .enumerate()
            .map(|(i, v)| ((i + 1).to_string(), v.clone()))
            .collect();
        let entries: Vec<(&str, &str)> =
            keys.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
        let out = upsert_section_text(text, "hidden", &entries);

        let cfg = Config::from_text(&out);
        assert_eq!(cfg.list_values("hidden"), vec!["a", "c"]);
        assert!(out.contains("# top"));
        assert!(cfg.general_flag("start_menu", false));
    }

    #[test]
    fn general_flag_write_back_replaces_in_place() {
        let text = "# top\n[general]\n# keep this comment\nstart_menu = true\n\
                    start_on_startup = true  # trailing note\n\n[plugins]\nsearch = true\n";
        let out = upsert_key_text(text, "general", "start_on_startup", "false");
        assert!(out.contains("# keep this comment"));
        assert!(out.contains("start_menu = true"));
        assert!(out.contains("search = true"));
        // The trailing comment survives the rewrite.
        assert!(out.contains("start_on_startup = false  # trailing note"), "{out}");

        let cfg = Config::from_text(&out);
        assert!(!cfg.general_flag("start_on_startup", true));
        assert!(cfg.general_flag("start_menu", false));
    }

    #[test]
    fn general_flag_write_back_adds_missing_key_and_section() {
        // Key absent, section present.
        let added = upsert_key_text("[general]\nstart_menu = true\n", "general", "tray_icon", "false");
        assert!(!Config::from_text(&added).general_flag("tray_icon", true));

        // Section absent entirely.
        let fresh = upsert_key_text("[plugins]\nsearch = true\n", "general", "tray_icon", "true");
        let cfg = Config::from_text(&fresh);
        assert!(cfg.general_flag("tray_icon", false));
        assert!(cfg.plugin_enabled("search"));
    }

    #[test]
    fn general_flag_write_back_ignores_same_key_in_another_section() {
        let text = "[general]\ntray_icon = true\n\n[plugins]\ntray_icon = true\n";
        let out = upsert_key_text(text, "general", "tray_icon", "false");
        assert!(!Config::from_text(&out).general_flag("tray_icon", true));
        // The [plugins] entry of the same name is untouched.
        assert!(Config::from_text(&out).plugin_enabled("tray_icon"));
    }

    #[test]
    fn general_flags() {
        let cfg = Config::from_text("[general]\nstart_menu = false\n");
        assert!(!cfg.general_flag("start_menu", true));
        assert!(cfg.general_flag("start_on_startup", true));
        assert!(!cfg.general_flag("unknown", false));
    }

    #[test]
    fn key_names() {
        assert_eq!(parse_key("a"), Some(0x41));
        assert_eq!(parse_key("Z"), Some(0x5A));
        assert_eq!(parse_key("7"), Some(0x37));
        assert_eq!(parse_key("f1"), Some(0x70));
        assert_eq!(parse_key("f24"), Some(0x87));
        assert_eq!(parse_key("f25"), None);
        assert_eq!(parse_key("space"), Some(0x20));
        assert_eq!(parse_key("nope"), None);
    }

    #[test]
    fn alias_upsert_creates_section() {
        let text = "# header\n[general]\nstart_menu = true\n";
        let out = upsert_alias_text(text, "tt", "Terminal.App");
        assert!(out.contains("# header"));
        assert!(out.contains("[aliases]"));
        assert!(out.contains("tt = \"Terminal.App\""));
        let cfg = Config::from_text(&out);
        assert_eq!(cfg.aliases_map().get("tt").unwrap(), "Terminal.App");
    }

    #[test]
    fn alias_upsert_replaces_same_alias_and_same_app() {
        let text = "[aliases]\ntt = \"Old.App\"\nvs = \"Code.App\"\n\n[plugins]\nsearch = true\n";
        let out = upsert_alias_text(text, "tt", "New.App");
        assert!(out.contains("tt = \"New.App\""));
        assert!(!out.contains("Old.App"));
        assert!(out.contains("vs = \"Code.App\""));
        // re-aliasing the same app under a new name drops the old alias
        let out2 = upsert_alias_text(&out, "code", "Code.App");
        assert!(!out2.contains("vs = "));
        assert!(out2.contains("code = \"Code.App\""));
        // untouched sections survive
        assert!(out2.contains("[plugins]"));
        assert!(out2.contains("search = true"));
    }

    #[test]
    fn alias_remove() {
        let text = "[aliases]\ntt = \"Terminal.App\"\nvs = \"Code.App\"\n";
        let out = remove_alias_text(text, "Terminal.App");
        assert!(!out.contains("tt"));
        assert!(out.contains("vs = \"Code.App\""));
    }

    #[test]
    fn modifier_combos() {
        assert_eq!(parse_mods("ctrl"), Some(0x2));
        assert_eq!(parse_mods("Ctrl+Shift"), Some(0x6));
        assert_eq!(parse_mods("win+alt"), Some(0x9));
        assert_eq!(parse_mods("none"), Some(0));
        assert_eq!(parse_mods("hyper"), None);
    }
}
